### ISSUE TITLE
Acknowledements

### ISSUE THREAD

**Issue by 0xworks** [Ershany/Arcane-Engine#30]
Looks like you took a bit of inspiration from the Hazel game engine series.  I appreciate that you've gone your own way on quite a bit of it, but I think an acknowledgement of the game engine series in this project's readme is probably appropriate :-)

**Comment by Ershany** [comment]
Good point, I have other sources credited already, I used a couple things from the YouTube series as inspiration so I will go ahead and add that in.

**Comment by 0xworks** [comment]
Thanks 👍
